## --------------------
## DON'T EDIT THIS FILE
## --------------------
## Engine: yamlinc@0.1.10
## Source: reference/masterYaml.yaml

openapi: 3.0.0
info:
  title: Flight List and Numbers
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /data:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    total: 7744k
                    comp1: 262k
                    comp2: 739k
                    comp3: 850K
                    comp4: 946K
                    compView: 86.9K
                    purRate: '86'
                    checRate: '36'
                    aRate: '67'
                    amazon: '897'
                    flip: '837'
                    ebay: '894'
              schema:
                $ref: /reference/models/dataConfig.yaml
title: Flight
type: object
properties:
  total:
    type: string
    example: 3823K
    pattern: '^[1-9][1-9][1-9][1-9][K]$'
  comp1:
    type: int
    example: 382
    pattern: '^[1-9][1-9][1-9][K]$'
  comp2:
    type: int
    example: 382
    pattern: '^[1-9][1-9][1-9][K]$'
  comp3:
    type: int
    example: 382
    pattern: '^[1-9][1-9][1-9][K]$'
  comp4:
    type: string
    example: 38.2K
    pattern: '^[1-9][1-9][.][1-9][K]$'
  compView:
    type: string
    example: 38.2K
    pattern: '^[1-9][1-9][.][1-9][K]$'
  purRate:
    type: string
    example: '38'
    pattern: '^[0-9][0-9]$'
  checRate:
    type: string
    example: '38'
    pattern: '^[0-9][0-9]$'
  aRate:
    type: string
    example: '38'
    pattern: '^[0-9][0-9]$'
  amazon:
    type: string
    example: 38.2K
    pattern: '^[1-9][1-9][.][1-9][K]$'
  flip:
    type: string
    example: 38.2K
    pattern: '^[1-9][1-9][.][1-9][K]$'
  ebay:
    type: string
    example: 38.2K
    pattern: '^[1-9][1-9][.][1-9][K]$'
