  
openapi: 3.0.0
info:
  title: Random Data by prism
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /flightLists:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    flight1: AIR_INDIA1
                    codeNumber1: F2GLK5
                    flight2: AIR_INDIA2
                    codeNumber2: F2GLK5
                    flight3: AIR_INDIA3
                    codeNumber3: F2GLK5
                    flight4: AIR_INDIA4
                    codeNumber4: F2GLK5
                    flight5: AIR_INDIA5
                    codeNumber5: F2GLK5

                   
              schema:
                $ref: /reference/models/dataConfig.yaml