  
openapi: 3.0.0
info:
  title: Flight List and Numbers
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /data:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    total: 7744k
                    comp1: 262k
                    comp2: 739k
                    comp3: 850K
                    comp4: 946K
                    compView: 86.9K
                    purRate: '86'
                    checRate: '36'
                    aRate: '67'
                    amazon: '897'
                    flip: '837'
                    ebay: '894'
                  
              schema:
                $ref: /reference/models/dataConfig.yaml